[build]
publish = "website"
command = ""  # No build command needed for static site

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NODE_VERSION = "18"  # Specify Node version for Netlify environment